Repository Metta-AI/metta, pull requests merged in 2025-05, with the labels that each got.

#238 feat: map previews
  metta/sim/map_preview.py
  metta/util/config.py
  metta/util/s3.py
  tools/train.py
Labels: 📦 ready

#415 fix: debug python CI
  .github/workflows/py-checks.yml
  devops/skypilot/config/train.yaml
Labels: 🐛 bug, 📦 ready, 🚽 skibidi

#449 feat: Fast GAE Implementation Unit Tests and Improvements
  Makefile
  metta/rl/fast_gae/fast_gae.pyi
  metta/rl/fast_gae/fast_gae.pyx
  setup.py
  tests/rl/fast_gae/test_fast_gae.py
Labels: 📦 ready

#461 feat: Add Parallel Mac Hardware Configuration
  configs/hardware/mac_parallel.yaml
  configs/hardware/mac_serial.yaml
  configs/hardware/macbook.yaml
Labels: 📦 ready

#463 fix: minor changes from 404
  .gitignore
  .vscode/c_cpp_properties.json
  configs/user/rwalters.yaml
  devops/sandbox/setup_vscode_workspace.sh
  devops/setup_build.sh
  metta/rl/pufferlib/trainer.py
Labels: 📦 ready

#405 feat: optimize distribution utils
  .vscode/launch.json
  metta/agent/util/distribution_utils.py
  mettagrid/benchmarks/test_mettagrid_env_benchmark.py
Labels: 📦 ready

#478 feat: move custom resolvers to `metta`
  configs/common.yaml
  configs/user/rwalters.yaml
  metta/util/__init__.py
  metta/util/resolvers.py
  mettagrid/benchmarks/test_mettagrid_env_benchmark.py
  mettagrid/mettagrid/__init__.py
  mettagrid/mettagrid/mettagrid_env.py
  mettagrid/tests/test_basic.py
  tests/util/test_resolvers.py
  tools/map/gen.py
Labels: 📦 ready

#496 hotfix: resolver registration in multiprocessor VecEnv runs
  metta/sim/vecenv.py
  metta/util/resolvers.py
Labels: 🐛 bug

#498 chore: add types to Experience
  metta/rl/pufferlib/experience.py
  metta/rl/pufferlib/trainer.py
Labels: 📦 ready

#459 feat: add debug utils for saving c data
  mettagrid/mettagrid/util/debug.py
  mettagrid/tests/mettagrid_test_args_env_cfg.json
  mettagrid/tests/mettagrid_test_args_env_map.txt
  tests/map/test_node.py
Labels: 📦 ready

#511 hotfix: restore map labels
  mettagrid/mettagrid/config.py
  mettagrid/mettagrid/mettagrid_env.py
Labels: 📦 ready

#513 feat: add a cspell management script
  .cspell.json
  devops/sandbox/merge_cspell.py
  metta.code-workspace
Labels: ready 📦

#520 fix: mettagrid build system
  .github/actions/setup-python-uv/action.yml
  .github/workflows/cpp-checks.yml
  .github/workflows/py-checks.yml
  CLAUDE.md
  Makefile
  devops/aws/setup_aws_profiles.sh
  devops/build_mettagrid.sh
  devops/setup_build.sh
  mettagrid/Makefile
  mettagrid/mettagrid/mettagrid_c.hpp
  mettagrid/pyproject.toml
  mettagrid/setup.py
  mettagrid/tests/test_mettagrid.cpp
  mettagrid/uv.lock
  pyproject.toml
  requirements_pinned.txt
  setup.py
  uv.lock
Labels: ready 📦

#516 feat: lstm layer unit test
  metta/agent/lib/actor.py
  metta/agent/lib/metta_layer.py
  metta/agent/lib/nn_layer_library.py
  tests/agent/lib/test_lstm.py
Labels: ready 📦

#605 hotfix: fix bad map with new ascii map test
  configs/env/mettagrid/maps/object_use/swap_out.map
  tests/map/test_validate_all_ascii_maps.py
Labels: ready 📦

#597 chore: tidy devops scripts
  devops/aws/batch/entrypoint.sh
  devops/sandbox.sh
  devops/setup.env
  devops/setup_build.sh
  devops/skypilot/config/sandbox.yaml
  devops/skypilot/config/sk_train.yaml
  devops/sweep.sh
  devops/sweep_rollout.sh
  devops/train.sh
Labels: ready 📦

#586 feat: git-history-trainer script
  .gitignore
  devops/tools/git-history-trainer.sh
  devops/tools/merge_cspell.py
Labels: ready 📦

#568 fix: update mettagrid makefile to track header files
  .github/workflows/cpp-checks.yml
  .github/workflows/py-checks.yml
  mettagrid/Makefile
Labels: ready 📦

#601 fix: repair training
  metta/agent/metta_agent.py
  metta/agent/util/distribution_utils.py
  metta/rl/pufferlib/trainer.py
  tests/agent/test_metta_agent.py
  tests/agent/util/test_distribution_utils.py
Labels: ready 📦

#623 Fix dcss directory path in README
  README.md
Labels: codex

#621 Fix S3 save_to_uri bug and add tests
  metta/map/utils/storage.py
  tests/map/utils/test_storage.py
Labels: codex

#628 Add AGENTS usage guidelines
  AGENTS.md
Labels: codex

#626 Add MIT license file
  LICENSE
Labels: codex

#627 Add pre_test script for Codex
  .codex/pre_test.sh
Labels: codex

#625 Add test for invalid logit index in MettaAgent
  tests/agent/test_metta_agent.py
Labels: codex

#624 Fix typo in worldmap comment
  mettascope/src/worldmap.ts
Labels: codex

#643 feat: add mettagrid unit test for moving and collecting a heart
  mettagrid/tests/actions.py
  mettagrid/tests/test_actions.py
  mettagrid/tests/test_heart_collection.py
Labels: ready 📦

#593 feat: Claude AI Code Review Workflows
  .github/workflows/review-comments.yml
  .github/workflows/review-type-annotations.yml
  devops/aws/batch/entrypoint.sh
Labels: ready 📦

#650 hotfix: fail gracefully when policies don't match env
  metta/agent/policy_store.py
  metta/sim/simulation.py
  metta/sim/simulation_suite.py
Labels: ready 📦

#655 fix: Add `--reset` flag to AWS setup for sso migration
  devops/aws/README.md
  devops/aws/batch/register_job_definition.py
  devops/aws/setup_aws_profiles.sh
Labels: ready 📦

#648 feat: allow aws launch from subdirs
  devops/aws/batch/launch_task.py
  metta/util/fs.py
Labels: ready 📦

#662 Add git-pr helper
  git-pr
Labels: codex

#673 Disable smoke test
  .github/workflows/py-checks.yml
Labels: codex

#674 Add TLDR section to Claude CI prompts
  .github/workflows/review-comments.yml
  .github/workflows/review-type-annotations.yml
Labels: codex

#664 Allow UTF characters in maps
  configs/env/mettagrid/maps/navigation/radial_mini.map
  configs/env/mettagrid/maps/navigation_sequence/radial_mini.map
  map_editor_ui/script.js
  metta/map/scenes/inline_ascii.py
  metta/map/utils/storable_map.py
  mettagrid/mettagrid/room/ascii.py
  tests/map/utils/test_unicode_map_loading.py
Labels: codex

#661 Add heartbeat monitor for SkyPilot jobs
  devops/train.sh
  metta/util/heartbeat.py
  tools/train.py
Labels: codex

#701 Add runtime arg type validation
  metta/util/__init__.py
  metta/util/validate.py
  tests/util/test_validate_arg_types.py
Labels: codex

#700 Add einops review workflow
  .github/workflows/review-einops.yml
Labels: codex

#691 Fix merge layer error
  metta/agent/lib/merge_layer.py
Labels: codex

#712 fix: add rewards unit test
  .github/workflows/aws-train.yml
  .github/workflows/checks.yml
  .github/workflows/claude.yml
  .github/workflows/review-comments.yml
  .github/workflows/review-einops.yml
  .github/workflows/review-readme.yml
  .github/workflows/review-type-annotations.yml
  devops/aws/setup_aws_profiles.sh
  mettagrid/Makefile
  mettagrid/benchmarks/test_grid_object_benchmark.cpp
  mettagrid/mettagrid/mettagrid_c.cpp
  mettagrid/mettagrid/mettagrid_c.hpp
  mettagrid/mettagrid/mettagrid_c.pyi
  mettagrid/mettagrid/mettagrid_env.py
  mettagrid/tests/actions.py
  mettagrid/tests/run_cpplint.sh
  mettagrid/tests/test_actions.py
  mettagrid/tests/test_basic.py
  mettagrid/tests/test_buffers.py
  mettagrid/tests/test_grid_object.cpp
  mettagrid/tests/test_heart_collection.py
  mettagrid/tests/test_mettagrid.cpp
  mettagrid/tests/test_mettagrid.py
  mettagrid/tests/test_rewards.py
Labels: ready 📦

#606 Adds new battery colors
  configs/env/mettagrid/mettagrid.yaml
  configs/env/mettagrid/navigation/training/terrain_from_numpy.yaml
  configs/env/mettagrid/navigation/training/varied_terrain_balanced.yaml
  configs/env/mettagrid/navigation/training/varied_terrain_dense.yaml
  configs/env/mettagrid/navigation/training/varied_terrain_maze.yaml
  configs/env/mettagrid/navigation/training/varied_terrain_sparse.yaml
  configs/env/mettagrid/object_use/evals/full_sequence.yaml
  configs/env/mettagrid/object_use/evals/generator_use.yaml
  configs/env/mettagrid/object_use/evals/generator_use_free.yaml
  configs/env/mettagrid/object_use/evals/lasery_use.yaml
  configs/env/mettagrid/object_use/training/easy_all_objects.yaml
  configs/env/mettagrid/object_use/training/terrain_from_numpy.yaml
  configs/env/mettagrid/object_use/training/varied_terrain.yaml
  configs/env/mettagrid/reward_dr.yaml
  metta/agent/lib/observation_normalizer.py
  mettagrid/configs/benchmark.yaml
  mettagrid/mettagrid/objects/constants.hpp
  mettagrid/tests/mettagrid_test_args_env_cfg.json
  mettagrid/tests/test_mettagrid.cpp
  run_evals.sh
Labels: 🥖 stale

#724 fix: clean up CI benchmarks
  .github/actions/call-bencher-api/action.yml
  .github/actions/combine-all-benchmarks/action.yml
  .github/workflows/checks.yml
  mettagrid/Makefile
  mettagrid/benchmarks/test_grid_object_benchmark.cpp
  mettagrid/benchmarks/test_mettagrid_env_benchmark.cpp
  mettagrid/benchmarks/test_mettagrid_env_benchmark.py
  mettagrid/mettagrid/mettagrid_env.py
  mettagrid/mettagrid/util/actions.py
  mettagrid/tests.cmake
  mettagrid/tests/cpplint.sh
  mettagrid/tests/test_actions.py
  mettagrid/tests/test_mettagrid.cpp
  mettagrid/tests/test_rewards.py
  tests/agent/util/test_distribution_utils.py
  tests/map/test_map_mapgen_benchmark.py
  tests/map/test_node.py
  tests/map/test_room_grid.py
  tests/rl/fast_gae/test_fast_gae.py
Labels: ready 📦

#608 Create help page for mettascope with improved content and styling
  configs/user/arikalinowski.yaml
  mettascope/data/ui/agent_controls.png
  mettascope/data/ui/help.png
  mettascope/data/ui/ui_explainer.png
  mettascope/index.html
  mettascope/mettascope_info.html
  mettascope/style.css
Labels: 🥖 stale

#728 Implement ascii renderer
  mettagrid/mettagrid/mettagrid_env.py
  mettagrid/mettagrid/renderer/renderer.py
  mettagrid/tests/test_basic.py
Labels: codex
