Repository Metta-AI/metta, pull requests merged in 2025-06, with the labels that each got.

#785 Replace mettagrid.util.file.efs_lock with metta.util.lock.run_once
  configs/sweep/fast.yaml
  configs/sweep/full.yaml
  configs/sweep_job.yaml
  configs/user/daveey.yaml
  metta/util/README.md
  metta/util/lock.py
  mettagrid/mettagrid/util/file.py
  tools/sweep_init.py
Labels: codex

#763 Refactor curriculum into module with specialized implementations
  .vscode/launch.json
  metta/rl/pufferlib/trainer.py
  mettagrid/mettagrid/curriculum.py
  mettagrid/mettagrid/curriculum/__init__.py
  mettagrid/mettagrid/curriculum/curriculum.py
  mettagrid/mettagrid/curriculum/low_reward.py
  mettagrid/mettagrid/curriculum/multi_task.py
  mettagrid/mettagrid/curriculum/progressive.py
  mettagrid/mettagrid/curriculum/random.py
  mettagrid/mettagrid/curriculum/sampling.py
  mettagrid/mettagrid/curriculum/util.py
  mettagrid/tests/test_curriculum.py
  mettagrid/tests/test_multi_task_curriculum.py
  mettagrid/uv.lock
Labels: codex

#803 Add --no-spot option
  devops/skypilot/launch.py
Labels: codex

#807 Trim mettagrid deps
  .python-version
  mettagrid/pyproject.toml
  pyproject.toml
Labels: codex

#779 feat: improved training time metrics
  metta/rl/pufferlib/trainer.py
  metta/util/timing.py
Labels: ready 📦

#824 hotfix: make docker logs wider
  Makefile
  devops/docker/Dockerfile.base
  devops/docker/build.sh
  metta/rl/pufferlib/trainer.py
  metta/util/logging.py
  metta/util/runtime_configuration.py
Labels: ready 📦

#811 fix: add types.hpp to mettagrid c env
  .github/workflows/checks.yml
  devops/tf/eks/cert-manager-configs/templates/clusterissuer.yaml
  metta/agent/metta_agent.py
  metta/rl/pufferlib/trainer.py
  metta/sim/simulation.py
  mettagrid/mettagrid/mettagrid_c.cpp
  mettagrid/mettagrid/mettagrid_env.py
  mettagrid/mettagrid/types.hpp
  mettagrid/mettagrid/util/actions.py
  mettagrid/tests/test_actions.py
  mettagrid/tests/test_basic.py
  mettagrid/tests/test_rewards.py
  run_evals.sh
  tests/util/test_resolvers.py
  tools/renderer.py
  tools/sim.py
Labels: ready 📦

#849 fix: turn off claude review compliments
  .github/scripts/claude_review.py
  .github/workflows/claude-review-base.yml
  .github/workflows/claude-review-orchestrator.yml
  docs/workflows/claude-review-system.md
Labels: ready 📦

#822 Add wandb tags and message support
  .vscode/settings.json
  configs/wandb/metta_research.yaml
  metta/util/wandb/wandb_context.py
  tests/util/wandb/test_wandb_context.py
Labels: codex

#925 Add episode completion, last action, and last reward to observations
  .cache/clangd/index/fast_gae.cpp.A2B57F33FA394ECE.idx
  mettagrid/mettagrid/mettagrid_c.cpp
  mettagrid/mettagrid/mettagrid_c.hpp
  mettagrid/mettagrid/objects/constants.hpp
  mettagrid/tests/test_mettagrid.py
Labels: codex

#927 feat: json formatting utility
  .claude/settings.local.json
  .cspell.json
  .prettierignore
  .prettierrc
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  devops/tools/format_json.sh
  metta.code-workspace
  mettagrid/CMakePresets.json
  mettamap/.eslintrc.json
  mettamap/import-sorter.json
  mettamap/tsconfig.json
  observatory/tsconfig.json
  observatory/tsconfig.node.json
Labels: ready 📦

#965 Fix SPS calculation after checkpoint
  metta/rl/pufferlib/profile.py
  metta/rl/pufferlib/trainer.py
Labels: codex

#874 fix: add timing to environment
  metta/rl/trainer.py
  metta/util/git.py
  mettagrid/mettagrid/curriculum/curriculum.py
  mettagrid/mettagrid/mettagrid_env.py
  mettagrid/mettagrid/util/dict_utils.py
  mettagrid/mettagrid/util/stopwatch.py
  mettagrid/tests/util/test_stopwatch.py
Labels: wip 🚧

#815 feat: system monitor
  metta/rl/trainer.py
  metta/util/system_monitor.py
  mettagrid/benchmarks/test_mettagrid_env_benchmark.cpp
  pyproject.toml
  tests/util/test_system_monitor.py
Labels: ready 📦

#818 feat: initial map state hash
  .cspell.json
  .github/workflows/claude.yml
  mettagrid/benchmarks/test_mettagrid_env_benchmark.py
  mettagrid/configs/benchmark.yaml
  mettagrid/configs/test_basic.yaml
  mettagrid/mettagrid/hash.hpp
  mettagrid/mettagrid/mettagrid_c.cpp
  mettagrid/mettagrid/mettagrid_c.hpp
  mettagrid/mettagrid/mettagrid_c.pyi
  mettagrid/mettagrid/mettagrid_env.py
  mettagrid/mettagrid/replay_writer.py
  mettagrid/tests/test_mettagrid.py
Labels: ready 📦

#1104 fix: save and load timing state in training checkpoints
  .cspell.json
  common/src/metta/common/stopwatch.py
  common/tests/test_stopwatch.py
  metta/agent/policy_store.py
  metta/rl/trainer.py
  metta/rl/trainer_checkpoint.py
  mettagrid/src/metta/mettagrid/mettagrid_c_config.py
  mettagrid/tests/test_curriculum.py
  pyproject.toml
  pyrightconfig.json
Labels: ready 📦

#1198 Fix train script exit code
  devops/train.sh
Labels: codex
